using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace WJX {
    public enum AIState{
        NULLAITYPE = 0,
        DISPERSEAI,//分散AI
		PAINT,
		LEVEL2PAINT,


		LEVEL3BAGLIGATURE1,
		LEVEL3BAGLIGATURE2,
		LEVEL3BAGLIGATURE3,


		LEVEL3COLORAINT,
		LEVEL3SWIPINGCARD,
		MODELAI,
		LEVEL6NAIL1PAINT,
		LEVEL6NAIL2PAINT,
		LEVEL6NAIL3PAINT,
		LEVEL6NAIL4PAINT,
		LEVEL6NAIL5PAINT,
		LEVEL7PAINT,
		TIP

    }

    public enum AIStateID{
        NULLAIID = 0,
        DISPERSEAIID,
		PAINTID,
		LEVEL2PAINTID,

		LEVEL3BAGLIGATURE1ID,
		LEVEL3BAGLIGATURE2ID,
		LEVEL3BAGLIGATURE3ID,

		LEVEL3COLORAINTID,
		LEVEL3SWIPINGCARDID,
		MODELAIID,
		LEVEL6NAIL1PAINTID,
		LEVEL6NAIL2PAINTID,
		LEVEL6NAIL3PAINTID,
		LEVEL6NAIL4PAINTID,
		LEVEL6NAIL5PAINTID,
		LEVEL7PAINTID,
		TIPID
    }
}



